In [7]:
import numpy as np

### Write a function so that the columns of the output matrix are powers of the input vector.

In [12]:
def matrix ():
    x=np.array([1,2,3,4,5,6,7,8,9,10])
    n= 3
    i= True 
    print (np.vander(x,n,i))
matrix()

[[  1   1   1]
 [  1   2   4]
 [  1   3   9]
 [  1   4  16]
 [  1   5  25]
 [  1   6  36]
 [  1   7  49]
 [  1   8  64]
 [  1   9  81]
 [  1  10 100]]


### Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [18]:
def moving_average(a, n=3) :
    sum = np.cumsum(a, dtype=float)
    sum[n:] = sum[n:] - sum[:-n]
    return sum[n - 1:] / n
a = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
print(moving_average(a, n=3))

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
